### PR TITLE
Getting started with some files nabbed and updated from other feathers projects

### PR DESCRIPTION
**Pull request by appurist**
### First pass at most of the files

Most of the contents of this commit was grabbed from feathers-memory, feathers-nedb, or feathers-mongodb and I noticed some upstream commits while working on feathers-redis that were general cleanup of all feathers projects.

So I wanted to at least get all these misc files committed from my start on feather-redis so that if @corymsmith or any of the others who were doing Awk cleanup of all projects wanted to include this one, it would be here and then I wouldn't be committing another one later that didn't follow the cleanup pattern.

This doesn't include all the files yet (e.g. nothing from lib/ or the example app, so it won't pass tests yet. 

If that's a problem for automation (I'm not sure), feel free to remove any files that trigger that, for example if having a .travis.yml or anything else causes an automation failure.  Or just reject the PR for now and just let me know here in the comments what the problem is. 

Also, I grabbed these from other projects but that doesn't necessarily mean they are what you want. ;)

WIP: I'm just trying to get the common files in here in case you have cross-project updates, etc, e.g. as in the rimraf updates.  I'll get the meaty files submitted in a follow-up PR.

### CODE REVIEW

**Comment by appurist** [comment]
Hmm, the readme really should indicate that it's still a work in progress and incomplete. Also the example code in the readme is not correct yet.

**Comment by daffl** [comment]
💥 I also added you as a collaborator to this repository so you can work on it directly.

**Comment by corymsmith** [comment]
@appurist I'll add the CodeClimate and Slack token to the Travis file in a few mins here

**Comment by appurist** [comment]
Thanks folks.  I'm fairly new to this but there are good example adapters out there and I'm been a server developer since '84 so I should be able to get it done. ;) But I'll try to get something committed over the next week or so that doesn't add to the burden of the rest of you for _too_ much fixup, cleanup, etc. And I can do the cleanup if you point out that something should be done differently.

@daffl @corymsmith I'm not sure of the Feathers collaborator process; should I be pushing into _branches_ and doing PRs and waiting, merging those PRs into `master` myself, or pushing directly to `master`?  (I see @corymsmith pushed directly but he was doing soooo much widespread updates to all the projects that I can easily see that was a special case.)  I also don't mind doing it from my own fork, although direct is faster if I don't need to wait for a PR merge.

**Comment by daffl** [comment]
What I usually do is to work directly on master until the first release and with pull requests after that. We can also take care of the npm release if you'd like.

**Comment by appurist** [comment]
That sounds ideal. I'll work on `master` for now until the first pass is complete, then PR from my fork.  

And yes, I agree you folks should handle the npm and do the publish/release whenever you determine is the best timing for things; I'm here to try to help where I can.  Okay thanks, now to get something actually done. 😁

**Pull request merged**
